import React, { useMemo, useRef, useState } from "react";
import * as XLSX from "xlsx";

/* ============ dados de exemplo (Pouso Alegre SVC / Julho) ============ */
const EXAMPLE_EMPS = [["ABNER JOVANI TOLEDO RODRIGUES","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","F|P|P|DSR||DSR|FJ|P|P|P|P|DSR|F|F|F|P|P|||F|P|P|DSR||||||||"],["ADRIANA DOS SANTOS BARREIROS","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","F|F|F|DSR||P|F|F|DSR|DSR|F|F|F|DSR|DSR|F|F|F|F|DSR|P|F|F||||||||"],["ALEXANDRE KOTCHENKO LUCCHESI RANGEL","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","|P|P|P|P|P|P|F|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV"],["ANA CLAUDIA DE OLIVEIRA MARQUES","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","|F|F|F||F||||||DSR|F|F|F|DSR|DSR|F|F|F|DSR|DSR|||||||||"],["ANA GABRIELLY PAIVA RIBEIRO","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|DSR|DSR|DSR||P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|F|P||P|F|P|P||||||||"],["ANA KARLA GOMES DA SILVA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|F|P|P||DSR|P|P|P|P|F|DSR|P|P|P|P|P|||P|P|P|DSR||||||||"],["ANA MARIA DE OLIVEIRA NETA FURTADO","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P|P|P||P|P|P|P||||||||"],["ANDERSON MARCELO DOS SANTOS SOUZA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|P|P|P||P|FJ|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|F|DSR|P|P|P||||||||"],["ANDERSON RAFAEL BERALDO DA SILVA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|DSR|DSR|P|F|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|F||||||||"],["ANDIANARA CRISTINA MOREIRA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","F|F|F|DSR||F|F|F|DSR|DSR|F|F|P|DSR|DSR|F|P|F|F|DSR|F|P|F||||||||"],["ANDRESSA CRISTINA TELLES ESTEVES","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","F|P|P|||P|P|F|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P|DSR|DSR|P||||||||"],["ANGELICA MARIA DA SILVA CECILIO LIMA","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","|||||||P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P||||||||"],["ARIELLE RAMILLY BISPO DA SILVA","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","|F|P|DSR|DSR|F|P|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF"],["BEATRIZ CABRAL DA PAIXAO","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","|||||||P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|F|DSR|DSR|P||||||||"],["BIANCA DOS SANTOS NOGUEIRA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|P|P|P||P|P|DSR|DSR|P|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P||||||||"],["BRENDOR WASHINGTON BATISTA DA CUNHA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","||||||||P|P|P|P|DSR|P|P|P|P|P||P|P|F|F||||||||"],["BRUNA GABRIELY ALMEIDA SORANSO","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|P|P|DSR||F|P|F|P|F|DSR|DSR|F|F|F|DSR|DSR|F|F|F|DSR|DSR|F||||||||"],["BRUNO DA SILVA RAYMUNDO","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|DSR|P|P|P|F|P|P|P|P|DSR|P|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P||||||||"],["BRUNO RUAN NASCIMENTO FERREIRA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|P|P|P||P|DSR|DSR|P|P|DSR|P|P|P|P|P|P|P||P|P|P|P||||||||"],["BRUNO SOUZA NOGUEIRA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","F|DSR|DSR|F|F|F|DSR|DSR|F|F|F|DSR|DSR|F|F|F|||||||||||||||"],["CAMILLY VITORIA ASSIS ARANTES","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|P|P|P|P|DSR|DSR|DSR|P|P|P|P|P|P|P|P|P|P||P|P|P|P||||||||"],["CARLA MARIA DA SILVA","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","||||||P|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P||||||||"],["CARLOS DANIEL FERREIRA DA COSTA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","|P||P||P|P|F|DSR|DSR|P|P|F|DSR|DSR|P|P|F|F|DSR|P|F|P||||||||"],["CARLOS EDUARDO ROSA DA SILVA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","|||||||||||||||||||P|F|P|DSR||||||||"],["CARLOS FILIPE MACIENTE","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","FJ|DSR|DSR|P|P|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P||||||||"],["CARLOS GABRIEL SOARES RIBEIRO","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|F|P|F||DSR|P|P|P|P|P|DSR|P|P|F|F|P|||DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF"],["CARLOS TADEU GUSMAO DE ALMEIDA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|P|P|P|DSR|P|P|P|P|P|DSR|P|P|P|P|P|||P|P|P|DSR||||||||"],["CASSIA FLORENTINO SANTOS","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|F|P|P||F|DSR|DSR|P|P|F|P|DSR|P|P|P|P|P||P|P|P|F||||||||"],["CAUANE FRANCISCA ROSA DOS SANTOS","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","F|F|F|DSR||F|P|P|DSR|P|F|F|P|DSR|DSR|DSR|DSR|P|F|DSR|P|P|P||||||||"],["CESAR AUGUSTO CASTELAO NETO","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","F|F|F|F||F|F|F|F|F|DSR|DSR|F|F|DV|DSR|DSR|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV|DV"],["CICERO RUBENS NOGUEIRA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|P|DSR||DSR|FJ|P|P|P|P|DSR|P|P|P|P|P|||P|P|P|DSR||||||||"],["CLAILTON WAGNER FERREIRA","A","OPERADOR DE EQUIPAMENTOS I","DANIEL PEREIRA","P|DSR|DSR|P|P|P|P|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P||||||||"],["CLAUDIO LUIZ RODRIGUES MEZA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","||||||||P|P|P|P|DSR|P|P|P|P|P||P|P|P|P||||||||"],["DAIANA DE FATIMA FERREIRA DIAS","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","||||||||P|P|DSR|DSR|F|P|P|DSR|DSR|F|F|P|DSR|DSR|P||||||||"],["DAMIANA BEZERRA DE ARAUJO","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|P|P|P||P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P||||||||"],["DANIEL GARCIA SILVESTRE DE ALMEIDA","D","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|DSR|DSR|P|P|DSR|P|P|P|P|P|DSR|P|P|P|P|P|||P|||DSR||||||||"],["DANIEL RIBEIRO VIEIRA","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","F|P|P|P||P|FJ|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|F|F|DSR|DSR|P||||||||"],["DANIELA CORDEIRO DE FRANCA","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|P|P|DSR||FJ|FJ|F|F|F|DSR|DSR|P|P|P|DSR|DSR|F|F|P|DSR|DSR|P||||||||"],["DANIELE FERREIRA MARCELINO","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","F|F|F|F||DSR|F|F|F|F|F|DSR|F|F|F|F|F|||F|F|F|DSR||||||||"],["DARLEIDE DA SILVA ARAUJO","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|P|DSR||DSR|P|P|P|P|P|DSR|P|P|P|P|P|||P|P|P|DSR||||||||"],["DAUZIRA SANTANA DA PAIXAO SANTOS","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|P|DSR||DSR|P|P|P|P|P|DSR|P|P|P|P|P|||P|P|P|DSR||||||||"],["DAVI FERREIRA DA SILVA","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","||||||||P|F|DSR|DSR|P|P|P|DSR|DSR|P|P|F|DSR|DSR|P||||||||"],["DIENE REGINA FERREIRA DOS SANTOS","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|P|P|P||F|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P||||||||"],["DOUGLAS FURTADO DE MENDONÇA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","||||||P|P|P|P|P|F|DSR|F|F|F|||||||||||||||"],["DOUGLAS PEREIRA FIUZA MORAIS","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|F|F|F||P|DSR|DSR|P|F|F|F|DSR|P|F|F|F|F||F|P|F|F||||||||"],["EDIMAR PEREIRA DA SILVA JUNIOR","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|DSR|DSR|P|F|P|FJ|P|P|P|DSR|DSR|P|P|F|DSR|DSR|P|F|P|DSR|DSR|P||||||||"],["ELIAS DE ALMEIDA TORRES","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|DSR|DSR|F|F|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|P|DSR|F|F|P||||||||"],["ELVIS RODOLFO VIEIRA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|P|F|P||F|F|DSR|P|P|F|F|DSR|P|P|P|P|P||P|P|F|F||||||||"],["EMMANUEL ALMEIDA RODRIGUES","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|P|P|DSR||P|DSR|DSR|P|P|P|P|DSR|P|P|P|P|P||P|P|P|P||||||||"],["ERIC RUAN FERNANDES","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|P|P|P|DSR|P|P|P|P|P|DSR|P|P|P|P|P|||P|P|P|DSR||||||||"],["EVELYN EMANUELLE APARECIDA LAURINDO","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","F|DSR|DSR|F|F|DSR|F|F|F|F|F|DSR|F|F|F|F|F|||F|F|F|DSR||||||||"],["EZEQUIAS CIRINO","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","||||||P|DF|P|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF"],["FABIANA FERREIRA MARTINS","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","F|F|F|P|DSR|F|P|F|F|F|DSR|DSR|F|P|P|DSR|DSR|P|P|P|DSR|DSR|P||||||||"],["FELIPE HENRIQUE DE SOUZA ROCHA","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|DSR|DSR|P|F|P|F|F|P|P|DSR|DSR|P|F|P|DSR|DSR|P|F|P|DSR|DSR|F||||||||"],["FELIPE MACIEL DOS SANTOS","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","F|F|F|DSR||DSR|F|F|F|F|F|DSR|F|F|F|P|F|||F|F|F|DSR||||||||"],["FELIPE NAZARIO OLIVEIRA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|FJ|P|DSR||F|DSR|DSR|F|P|P|P|DSR|P|P|P|P|P||P|P|P|P||||||||"],["FERNANDA DE ALMEIDA CASSEMIRO","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","|||||P|P|P|P|F|DSR|DSR|F|F|F|DSR|DSR|F|P|F|DSR|DSR|P||||||||"],["FERNANDO MARCOS MASSUCCI","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|P|P|F||P|P|P|P|F|DSR|DSR|P|P|P|DSR|DSR|F|F|F|DSR|DSR|P||||||||"],["FRANCISCO RODRIGUEZ ALVES","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|P|P|DSR|P|P|P|P|P|P|DSR|DSR|F|F|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF"],["GABRIEL APARECIDO MONTEIRO","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|DSR|DSR|P|P|P|P|P|P|DSR|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P||||||||"],["GABRIEL DE OLIVEIRA ALMEIDA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|P|P|DSR|P|P|P|F|DSR|DSR|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P||||||||"],["GABRIEL YURI CUSTODIO PEREIRA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|P|||DSR|FJ|P|P|F|F|DSR|P|P|P|P|P|||F|P|P|DSR||||||||"],["GABRIELA FERNANDES DA SILVA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","|||||||||||||||P|P|F||P|P|P|P||||||||"],["GABRIELA MARIA DE OLIVEIRA","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|P|P|P||F|P|P|P|F|DSR|DSR|P|P|P|DSR|DSR|P|F|F|DSR|DSR|P||||||||"],["GEIZA NITHIELY AURELIO CAMPOS","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","||||||P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P||||||||"],["GELIEL SANTOS FALCAO","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|P|P|DSR||P|DSR|DSR|P|P|P|P|DSR|P|P|P|P|P||P|P|P|P||||||||"],["GERALDO MAGELA GUIMARAES","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|FJ|P|DSR||P|DSR|DSR|P|P|P|P|DSR|P|P|P|P|P||P|P|P|P||||||||"],["GLASIELE CRISTINA DA SILVA REIS","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|P|P|P||P|DSR|DSR|P|P|P|F|DSR|F|P|P|P|P||F|F|F|P||||||||"],["GRAZIELE APARECIDA DE JESUS LIMA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|F|F||DSR|FJ|P|F|P|F|DSR|F|F|P|P|F|||F|F|F|DSR||||||||"],["GUILHERME CESAR DOS SANTOS","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|P|P||DSR|P|P|P|P|P|DSR|P|P|P|P|P|||P|P|P|DSR||||||||"],["GUILHERME LEANDRO TOLEDO LEITE","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|DSR|DSR|P|P|P|F|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|DSR|DSR|F||||||||"],["HELLEN CRISTINA ROSA BENTO CIPRIANO","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","||||||||||P|P|P|DSR|DSR|P|P|P|F|DSR|P|P|P||||||||"],["IGOR BATISTA SILVA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","F|P|P|F||P|F|P|P|DSR|P|P|F|DSR|DSR|P|P|P|F|DSR|F|P|P||||||||"],["INGRITE GONCALVES NUNES","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|P|P|DSR||F|DSR|DSR|P|F|P|P|DSR|P|F|P|P|F||P|P|P|P||||||||"],["ISADORA SAYURI SAKAMOTO SALOMON SANTOS","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|DSR|DSR|P|P|P|P|DSR|P|P|P|P|DSR|P|P|P|P|P||P|P|P|P||||||||"],["ISTEFANE BRUNA ALVES GARCIA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|P|P|||P|P|P|P|DSR|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P||||||||"],["ITALO SILVA DE OLIVEIRA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|P|DSR||DSR|P|P|P|P|P|DSR|P|P|P|P|P|||P|P|P|DSR||||||||"],["ITALO YAGO DAMETTO LIMA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|P|P|DSR||P|P|P|DSR|DSR|F|F|F|DSR|DSR|P|P|P|F|DSR|F|F|F||||||||"],["IVINA PAULA DA SILVA FERREIRA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","|||||||||||||||P|P|||P|P|P|DSR||||||||"],["JADER FRANCIS BENTO","D","AUXILIAR OPERACIONAL I","LEONARDO RODRIGO ALVES","P|DSR|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF"],["JADI MARIZA SOARES BALBINO","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","F|P|F|DSR||P|DSR|DSR|P|P|F|F|F|DSR|DSR|P|P|P|F|DSR|P|P|P||||||||"],["JALIELSON JOSE ALENCAR DA SILVA","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|P|DSR|DSR||P|P|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P||||||||"],["JANE CUSTODIO APARECIDO","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|P|P|DSR|F|P|DSR|DSR|P|P|P|P|DSR|P|P|P|P|P||P|P|P|P||||||||"],["JEFFERSON ARIEL CARNEIRO CLEMENTE","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","|||||||||||||||||||P|DSR|DSR|F||||||||"],["JENNIFER STEPHANY DOS SANTOS FERREIRA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|DSR|DSR|F|P|P|P|F|P|DSR|F|P|P|DSR|DSR|P|P|P|F|DSR|P|P|P||||||||"],["JOAO BATISTA DA SILVA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|P|P||DSR|P|P|P|P|P|DSR|P|P|P|P|P|||P|P|P|DSR||||||||"],["JOAO FRANCISCO DA CRUZ RODRIGUES","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","F|P|P|P||P|DSR|DSR|P|P|P|F|DSR|P|P|P|P|P||F|P|P|P||||||||"],["JOAO PEDRO FERNANDES BARBOSA","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","||||||||P|P|P|DSR|P|P|P|DSR|DSR|P|P|F|DSR|DSR|P||||||||"],["JOAO RICARDO TEIXEIRA DA COSTA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|F|P|P||F|F|F|DSR|DSR|P|P|P|DSR|DSR|F|F|F|F|DSR|F|F|F||||||||"],["JOBER RAIMUNDO DE SOUZA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","|||||F|P|F|P|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF"],["JOCELI APARECIDA NORONHA PAIVA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|P|DSR||DSR|P|P|P|P|P||P|P|P|P|P|||P|P|P|DSR||||||||"],["JOHNNY MICHEL SILVA BISPO","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|P|F|DSR|P|P|P|P|P|P|DSR|P|P|P|P|P|DSR|P|P|P|P|DSR|P||||||||"],["JONATHA LUIZ ANDRADE DOS SANTOS","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|P|P|P||P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P||||||||"],["JONATHAN DE PAULA ROCHA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","|||||||P|P|DSR|P|P|P|DSR|DSR|P|P|F|P|DSR|P|P|P||||||||"],["JOSE DE ALENCAR FONSECA REIS JUNIOR","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","F|DSR|P|F|F|F|P|P|P|P|F|F|DSR|F|F|F|F|F||F|P|P|F||||||||"],["JOSIANE PEREIRA DA SILVA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","F|P|P|P||P|DSR|DSR|P|P|P|P|DSR|P|P|P|P|P||P|P|P|P||||||||"],["JULIANO DAMIAO FRANCISCO","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","|P|P|DSR|F|F|P|P|F|F|F|DSR|F|F|F|P|F|||F|F|F|DSR||||||||"],["JUSSIMARA DE JESUS CORREIA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","||||||||P|DSR|P|P|P|DSR|DSR|P|P|P|F|DSR|P|P|F||||||||"],["KAIQUE VINICIUS DA SILVA SANTOS","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","||||||||P|P|P|P|F|P|P|P|P|||F|P|P|DSR||||||||"],["KAMILLY BEATRIZ DA SILVA PINTO","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","|||P|DSR|P|P|FJ|DSR|DSR|P|P|F|FJ|DSR|P|P|F|F|DSR|F|F|P||||||||"],["KASSANDRA DA SILVA MODESTO FABIANO","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|DSR|P|P||P|P|P|F|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P||||||||"],["KATHRYN NAYARA MARQUES","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","||||||||P|P|P|P|DSR|P|F|P|P|P||P|F|P|F||||||||"],["KAUA LUCAS RIBEIRO MOREIRA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|DSR|P|P|F|F|DSR|DSR|P|P|F|P|P|F|P|F|F|F||F|P|P|F||||||||"],["KELLERMAN VALERIANO LUNARDI","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|P|P|DSR||P|FJ|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|F|DSR|P|P|F||||||||"],["KENNYFER LUCAS DOS REIS SILVA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","|||||||||||||||P|P|||F|P|P|DSR||||||||"],["KETHILYN DE OLIVEIRA RIBEIRO","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|F|P|P||P|P|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|F|P|DSR|DSR|P||||||||"],["KETORY SAMARA DA SILVA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|P|P|DSR||P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P||||||||"],["KETRIN CORREA DE SOUZA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|P|DSR||DSR|P|P|F|F|F|DSR|F|F|F|F|F|||P|||||||||||"],["LARISSA CRISTINA MATHIAS DA SILVA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|P|P|P||P|DSR|DSR|P|P|P|F|DSR|P|P|P|P|P||P|P|P|P||||||||"],["LEANDRO DA SILVA SANTOS","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","|||||||||||||||P|P|||F|P||DSR||||||||"],["LILIANE EVANGELISTA PEREIRA DA SILVA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","|||||||||P|DSR|DSR|P|P|P|P|F|||P|F||DSR||||||||"],["LIRIEL DE PAIVA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","|||||||||||||||||||P|P|P|F||||||||"],["LIRIEL EMILY BORGES","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|P|||P|P|P|P|P|P|DSR|P|P|P|P|P|||P|P||DSR||||||||"],["LORRANY STEFANY PEREIRA DELFINO DE JESUS","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","F|F|P|F||DSR|F|F|F|F|F|DSR|F|P|F|F|F|||F|F|F|DSR||||||||"],["LUAN MIKAEL DE FARIA SILVA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","|||||||||||||||||||P|P|P|P||||||||"],["LUANA MARIA CUSTODIO","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","||||||||DSR|DSR|P|P|P|DSR|DSR|F|P|P|F|DSR|P|P|P||||||||"],["LUCAS ANGELI RODRIGUES","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|P|P|F||F|F|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P||||||||"],["LUCAS FERREIRA DA SILVA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","F|F|P|P||P|P|P|P|P|P|DSR|P|P|P|P|P|||P|P|P|DSR||||||||"],["LUCIA HELENA SANTANA DA SILVA MENDES","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","AL|AL|AL|AL|AL|AL|AL|AL|F|AL|AL|AL|F|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF"],["LUCIAN FELIPE VICENTE","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","||||||||||||||||P|||P|DSR|DSR|P||||||||"],["LUCIANO ALVES TOSCANO","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","AL|AL|AL|AL|AL|AL|AL|AL|AL|AL|AL|AL|DSR|AL|AL|AL|AL|F||AL|F|AL|F||||||||"],["LUCILENE DOS SANTOS","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|P|P|DSR||P|P|P|P|DSR|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P||||||||"],["LUIZ FELIPE DE JESUS BARBOSA SILVA","A","AUXILIAR OPERACIONAL I","LEONARDO RODRIGO ALVES","DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF"],["LUIZ FELIPE FERREIRA DA SILVA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","F|DSR|DSR|P|P|P|P|P|P|DSR|P|P|P|DSR|DSR|P|P|F|P|DSR|P|P|P||||||||"],["LUIZ GUSTAVO LAMOGLIA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|F|P|P||DSR|P|P|P|P|P||P|F|F|P|F|||F|F|P|DSR||||||||"],["MARCELA JUNIA LEONIDAS GOMES","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","||||||P|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P||||||||"],["MARCIELA THIERRU SILVA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|P|F|DSR||P|DSR|DSR|P|P|P|F|DSR|P|P|F|P|P||P|P|P|P||||||||"],["MARCOS OLIVEIRA LIMA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","|P|P|P|DSR|P|P|P|DSR|DSR|P||P|DSR|DSR|P|P|P|P|DSR|F|F|P||||||||"],["MARIA CLARA ALVES DE OLIVEIRA CAVALCANTE","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","|P|P|DSR|DSR|P|P|F|P|F|DSR|DSR|F|F|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF"],["MARIA EDUARDA TAVARES GOMES","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|F|P|P||P|P|P|P||||||||"],["MARIA IARA DA SILVA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","||||||||P|P|P|P|DSR|P|P|P|P|P||P|P|P|P||||||||"],["MARIA JOSE DA SILVA ALVES","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|P|P|P||P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P||||||||"],["MARIA JULIANA DOS SANTOS","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","|P|P|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P|P|P||P|P|P|F||||||||"],["MARIA LAURA DA SILVA RODRIGUES","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","|||||||P|P|P|P|P|DSR|P|P|P|P|P||F|P|P|P||||||||"],["MARIA VICTORIA AGDA CORREIA SILVA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|P|DSR||DSR|P|P|P|P|P|DSR|P|P|P|P|P|||P|P|P|DSR||||||||"],["MARIA VITORIA ALBERTO","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","F|DSR|DSR|F|F|DSR|F|P|F|F|F|DSR|F|F|F|F|F|||F|F|F|DSR||||||||"],["MARIA VITORIA DA SILVA","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|DSR|DSR|P|P|DSR|P|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P||||||||"],["MARIANA BEATRIZ DE SOUSA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","|||||||||||||||P|P|||P|P|P|DSR||||||||"],["MARIANA DE ALMEIDA SOUSA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|P|P|DSR||P|P|P|P|DSR|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P||||||||"],["MARIANA RODRIGUES DOS SANTOS","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|DSR|DSR|P|P|DSR|P|P|P|P|P|DSR|P|P|P|P|F|||P|P|P|DSR||||||||"],["MATEUS DA SILVA TEIXEIRA ESTEVAO","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|P|P|P||F|P|P|P|P|P|DSR|P|P|P|DSR|DSR|P|F|P|DSR|DSR|P||||||||"],["MATEUS MARCELINO DE BRITO","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|DSR|P|F|F|F|P|DSR|P|P|P|F|P|P|P|F|P|F||P|P|F|P||||||||"],["MATHEUS KEVYN FERREIRA DA SILVA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","F|||||||||||||||F|F|F|F|DSR|F|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF"],["MIRTENIS OLIVEIRA SAMPAIO","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","|P|P|DSR|DSR|P|F|F|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF"],["MIRVAN LINDER DA SILVA","A","AUXILIAR OPERACIONAL I","DANIEL PERREIRA","P|P|P|P||P|P|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|P||P||||||||"],["MONICA DE CASSIA SANTIAGO","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|P|P||DSR|P|P|P|P|P||P|P|P|P|P|||P|P|P|DSR||||||||"],["MONICA LORENCETTI","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","|||||||||P|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|F||||||||"],["NATALIANA APARECIDA DA SILVA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|P|P||DSR|P|P|P|P|F|DSR|P|P|F|FJ|FJ|||P|P|P|DSR||||||||"],["NAUDERLANIA CORDEIRO MORAES","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","|||||||||||||||P|P|||P|P|P|DSR||||||||"],["NEIVA LUCIA RODRIGUES","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|F|F|DSR||F|F|F||||||DSR|DSR|||||DSR|||||||||||"],["OSMAR ALVES DE SENNA JUNIOR","B","OPERADOR DE EQUIPAMENTOS I","LEONARDO ALVES","P|P|P|DSR|P|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P||||||||"],["PAULO CEZAR DE ALMEIDA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|P|P|P||P|DSR|DSR|P|P|P|P|DSR|P|P|P|P|F||P|P|P|P||||||||"],["PAULO ROBERTO DA SILVA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","||||||||||P|F|DSR|P|P|P|P|F||P|P|P|F||||||||"],["PRISCILA SILVA VILAS BOAS SIMOES","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|DSR|DSR|F|F|P|F|P|P|P|DSR|DSR|F|P|P|DSR|DSR|F|F|F|DSR|DSR|F||||||||"],["RAFAELA PRISCILA DA SILVA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|P|P|DSR|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P|P|P||P|P|P|P||||||||"],["RAIANE DO ROSARIO CARDOSO","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","|||||||||||||||DSR|DSR|F|P|P|DSR|DSR|P||||||||"],["RENATO CARLOS DELFINO","B","AUXILIAR OPERACIONAL I","DANIEL PERREIRA","DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF"],["RHUA LUCAS DA COSTA SOUZA MARTINS","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","F|P|F|P||F|DSR|DSR|P|P|P|P|DSR|P|P|F|P|F||F|P|F|F||||||||"],["RODOLFO LUIS SILVA MELO","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|P|F|P||P|DSR|DSR|F|F|F|DSR|DSR|F|F|F|F|P||P|P|F|P||||||||"],["RONALDO FERNANDES","?","AUXILIAR OPERACIONAL I","LEONARDO RODRIGO ALVES","F|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF"],["ROSILENE TEMOTEO VIANA","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|P|P|DSR||P|P|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P||||||||"],["SABRINA TUANY DE FATIMA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","||||||||||P||P|P|P|DSR|P|||P|P|P|DSR||||||||"],["SADRAQUE NORTIE DE CAMPOS MARCOLINO","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|P|P|DSR||P|FJ|P|P|P|DSR||P|P|P|DSR|DSR|P|P|P|DSR|DSR|P||||||||"],["SAMANTA EMILIANA GUEDES DO PRADO","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","||||||||||P||P|F|P|P|P|||P|F|P|DSR||||||||"],["SAMIRA RUTIELLY CAMARGO MARTINS","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|P|P|DSR||P|P|P|DSR|DSR|F||P|DSR|DSR|P|F|P|F|DSR|P|P|P||||||||"],["SAMUEL BORGES FERNANDES DE LIMA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","||||||||||F||F|DSR|DSR|F|F|F|F|DSR|F|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF"],["SAMUEL CARVALHO DOS SANTOS","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|P|P|P|P|P|P|F|P|DSR|F|P|P|DSR|DSR|P|P|P|F|DSR|P|F|P||||||||"],["SARA BISPO SANTOS","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|P|P|DSR||P|DSR|DSR|P|P|F||DSR|P|F|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF"],["SIDNEY ALVES PIMENTA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|DSR|DSR|P|P|P|P|P|DSR|DSR|P||P|DSR|DSR|P|P|P|P|DSR|P|P|P||||||||"],["SIMONE APARECIDA DOS SANTOS","D","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|P|P|P||DSR|P|P|P|P|P||P|P|P|P|P|F||P|P||DSR||||||||"],["SIMONE SANTOS FERREIRA MORAIS","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","||||||||||DSR||P|P|P|P|DSR|P|P|P|DSR|DSR|P||||||||"],["SOFIA RAMOS NORBERTO DOS SANTOS","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|P|P|P||P|P|F|DSR|DSR|P|P|P|DSR|DSR|P|P|P|F|DSR|P|P|P||||||||"],["SUELEN CRISTIANE MARIA DE OLIVEIRA","C","AUXILIAR OPERACIONAL I","DANIEL PERREIRA","P|P|P|P||F|DSR|P|P|P|P||DSR|P|P|P|P|P||P|P||P||||||||"],["SUELY APARECIDA CHAGAS","?","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","F|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF|DF"],["SUENDY TAMIRES GUEDES DE FÁTIMA","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","|||||||||||||||DSR|DSR|F|F|P|DSR|DSR|F||||||||"],["TAINA DA SILVA PINTO","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|F|P|P||DSR|P|P|P|P|F||P|P|P|P|P|||P|P|P|DSR||||||||"],["TAISSA CRISTINA DE OLIVEIRA","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","|||||||||||||||P|P|P|P|DSR|P|P|P||||||||"],["TATIANA SILVA PAIXAO","B","AUXILIAR OPERACIONAL I","LEONARDO ALVES","P|P|P|DSR|P|P|FJ|FJ|DSR|DSR|F|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P||||||||"],["TATIANE PEREIRA DA SILVA","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","||||||P|P|P|P|DSR||P|P|F|DSR|DSR|P|P|P|DSR|DSR|F||||||||"],["TAYGO EDUARDO PEREIRO","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|F|F|P||P|P|P|P|P|DSR||P|P|P|DSR|DSR|P|P|P|DSR|DSR|P||||||||"],["TELMA APARECIDA DE MENDONCA","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","F|P|P|DSR||P|P|F|P|P|DSR|P|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P||||||||"],["THAIS TELES DOS SANTOS LIMA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|P|P|P|P|P|DSR|DSR|P|P|P|P|DSR|P|P|P|P|P||P|P|P|P||||||||"],["THAMARA CRISTINA DE OLIVEIRA SENA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","|||||||P|F|F|F||F|F|P|P|F|||F|P|P|DSR||||||||"],["THIAGO LUIS SILVA SOUZA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","F|DSR|DSR|P|P|DSR|F|F|P|P|P||P|P|P|P|P|||P|P|P|DSR||||||||"],["VICTOR HUGO DE SOUZA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","|P|P|P|P|F|P|F|F|F|F||F|F|F|F|F|||F|F|P|DSR||||||||"],["VINICIUS DANILO GISOLFI DOS SANTOS","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|DSR|DSR|P|P|DSR|P|P|F|P|P||P|P|P|P|P|||P|P|P|DSR||||||||"],["VINICIUS MIGUEL DIAS DE ARRUDA","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|DSR||P|P|P|F|P|P|P|DSR||P|P|P|DSR|DSR|P|P|P|DSR|DSR|P||||||||"],["VITOR BRAGA TIBURCIO","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","|P|P|P|F|F|F|F|P|F|F||F|F|F|F|F|||F|F|P|DSR||||||||"],["VITOR RAFAEL MENDES","C","OPERADOR DE EQUIPAMENTOS I","MATHEUS HENRIQUE","P|P|P|P||P|DSR|DSR|P|P|P|F|DSR|P|P|P|P|P||P|P|P|P||||||||"],["VITORIA HELEN PEREIRA FIRMINO","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|DSR|DSR|P|F|P|FJ|P|P|P|DSR||P|P|P|DSR|DSR|P|F|P|DSR|DSR|P||||||||"],["VITORIA PATRICIA BEZERRA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","F|DSR|DSR|F||F|DSR|DSR|F|F|F||DSR|F|F|F|F||||||||||||||"],["WALDIRENE PEREIRA LEMES","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","||||||F|DSR|P|P|P|P|DSR|P|P|P|P|P||P|P|P|P||||||||"],["WELINGTON DA CUNHA RODRIGUES","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|P|||DSR|FJ|P|P|F|P||P|P|P|P|F|||P|P|P|DSR||||||||"],["WILLIAN SAMUEL CARDOSO MIRANDA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","||F|P|DSR|F|P|F|P|F|DSR|DSR|DSR|P|F|P|P|P||P|F|F|P||||||||"],["YASMIN DA SILVA PLACIDINO","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|P|DSR|DSR||F|FJ|P|P|P|P|P|F|P|P|DSR|DSR|P|F|P|DSR|DSR|F||||||||"],["YASMIN GARCIA FERNANDES","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|P|DSR||DSR|P|F|P|F|F|DSR|P|P|P|P|F|||P|P||DSR||||||||"],["YGOR DE PAULA SILVA","C","AUXILIAR OPERACIONAL I","MATHEUS HENRIQUE","P|DSR|DSR|F|F|P|DSR|DSR|P|P|F|P|DSR|P|F|P|P|F||F|F|F|F||||||||"],["YURI IGNACIO SILVA","D","AUXILIAR OPERACIONAL I","CARLOS EDUARDO ROQUE","P|P|P|DSR||DSR|P|P|P|P|P|DSR|P|P|P|P|P|||P|P||DSR||||||||"],["YURI TRENTINI GRISOTO","A","AUXILIAR OPERACIONAL I","DANIEL PEREIRA","P|P|P|DSR||P|P|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P|P|P|DSR|DSR|P||||||||"]];
const EXAMPLE_ESCALA_CSV = `Escala Julho - Pouso Alegre - SVC
Series ativas;A/B/C/D

1a semana (28/06 a 04/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;DSR;37;37;37;37;37
B;DSR;37;37;37;37;37;DSR
C;37;37;37;37;DSR;DSR;37
D;37;37;DSR;DSR;37;37;37
Total;74;111;111;111;111;111;111
Total c/ Over 20%;89;133;133;133;133;133;133
Presentes;74;111;111;107;87;94;71
HC S&OP;0;0;0;88;88;88;72
Folga;-74;-111;-111;-19;1;-6;1

2a semana (05/07 a 11/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;37;37;37;37;37;DSR
B;37;37;37;37;DSR;DSR;37
C;37;37;DSR;DSR;37;37;37
D;DSR;DSR;37;37;37;37;37
Total;74;111;111;111;111;111;111
Total c/ Over 20%;89;133;133;133;133;133;133
Presentes;31;80;86;89;117;101;92
HC S&OP;32;111;111;111;111;111;111
Folga;1;31;25;22;-6;10;19

3a semana (12/07 a 18/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;37;37;37;37;DSR;DSR;37
B;37;37;DSR;DSR;37;37;37
C;DSR;DSR;37;37;37;37;37
D;DSR;37;37;37;37;37;DSR
Total;74;111;111;111;111;111;111
Total c/ Over 20%;89;133;133;133;133;133;133
Presentes;63;101;103;98;110;105;98
HC S&OP;74;111;111;111;111;111;111
Folga;11;10;8;13;1;6;13

4a semana (19/07 a 25/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;37;37;DSR;DSR;37;37;37
B;DSR;DSR;37;37;37;37;37
C;DSR;37;37;37;37;37;DSR
D;37;37;37;37;DSR;DSR;37
Total;74;111;111;111;111;111;111
Total c/ Over 20%;89;133;133;133;133;133;133
Presentes;50;100;107;99;99;0;0
HC S&OP;74;111;111;111;111;111;111
Folga;24;11;4;12;12;111;111

5a semana (26/07 a 01/08);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;DSR;37;37;37;37;37
B;DSR;37;37;37;37;37;DSR
C;37;37;37;37;DSR;DSR;37
D;37;37;DSR;DSR;37;37;37
Total;74;111;111;111;111;111;111
Total c/ Over 20%;89;133;133;133;133;133;133
Presentes;0;0;0;0;0;0;111
HC S&OP;74;111;111;111;111;111;0
Folga;74;111;111;111;111;111;-111


Escala Julho - Pouso Alegre - Full
Series ativas;A/B

1a semana (28/06 a 04/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;DSR;4;4;4;4;4
B;DSR;4;4;4;4;4;DSR
Total;0;4;8;8;8;8;4
Total c/ Over 20%;0;5;10;10;10;10;5
Presentes;0;4;8;8;8;8;4
HC S&OP;0;0;0;0;0;0;0
Folga;0;-4;-8;-8;-8;-8;-4

2a semana (05/07 a 11/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;DSR;4;4;4;4;4
B;DSR;4;4;4;4;4;DSR
Total;0;4;8;8;8;8;4
Total c/ Over 20%;0;5;10;10;10;10;5
Presentes;0;4;8;8;8;8;4
HC S&OP;0;0;0;0;0;0;0
Folga;0;-4;-8;-8;-8;-8;-4

3a semana (12/07 a 18/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;DSR;4;4;4;4;4
B;DSR;4;4;4;4;4;DSR
Total;0;4;8;8;8;8;4
Total c/ Over 20%;0;5;10;10;10;10;5
Presentes;0;4;8;8;8;8;4
HC S&OP;0;0;0;0;0;0;0
Folga;0;-4;-8;-8;-8;-8;-4

4a semana (19/07 a 25/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;DSR;4;4;4;4;4
B;DSR;4;4;4;4;4;DSR
Total;0;4;8;8;8;8;4
Total c/ Over 20%;0;5;10;10;10;10;5
Presentes;0;4;8;8;8;8;4
HC S&OP;0;0;0;0;0;0;0
Folga;0;-4;-8;-8;-8;-8;-4

5a semana (26/07 a 01/08);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;DSR;4;4;4;4;4
B;DSR;4;4;4;4;4;DSR
Total;0;4;8;8;8;8;4
Total c/ Over 20%;0;5;10;10;10;10;5
Presentes;0;4;8;8;8;8;4
HC S&OP;0;0;0;0;0;0;0
Folga;0;-4;-8;-8;-8;-8;-4


Escala Julho - Pouso Alegre - XD
Series ativas;A

1a semana (28/06 a 04/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;33;33;33;33;33;DSR
Total;0;33;33;33;33;33;0
Total c/ Over 20%;0;40;40;40;40;40;0
Presentes;0;33;33;33;33;33;0
HC S&OP;0;0;0;0;0;0;0
Folga;0;-33;-33;-33;-33;-33;0

2a semana (05/07 a 11/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;33;33;33;33;33;DSR
Total;0;33;33;33;33;33;0
Total c/ Over 20%;0;40;40;40;40;40;0
Presentes;0;33;33;33;33;33;0
HC S&OP;0;0;0;0;0;0;0
Folga;0;-33;-33;-33;-33;-33;0

3a semana (12/07 a 18/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;33;33;33;33;33;DSR
Total;0;33;33;33;33;33;0
Total c/ Over 20%;0;40;40;40;40;40;0
Presentes;0;33;33;33;33;33;0
HC S&OP;0;0;0;0;0;0;0
Folga;0;-33;-33;-33;-33;-33;0

4a semana (19/07 a 25/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;33;33;33;33;33;DSR
Total;0;33;33;33;33;33;0
Total c/ Over 20%;0;40;40;40;40;40;0
Presentes;0;33;33;33;33;33;0
HC S&OP;0;0;0;0;0;0;0
Folga;0;-33;-33;-33;-33;-33;0

5a semana (26/07 a 01/08);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;DSR;33;33;33;33;33
Total;0;0;33;33;33;33;33
Total c/ Over 20%;0;0;40;40;40;40;40
Presentes;0;0;33;33;33;33;33
HC S&OP;0;0;0;0;0;0;0
Folga;0;0;-33;-33;-33;-33;-33


Escala Julho - Pouso Alegre - Consolidado
Series ativas;A/B/C/D

1a semana (28/06 a 04/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;DSR;37;37;37;37;37
B;DSR;37;37;37;37;37;DSR
C;37;37;37;37;DSR;DSR;37
D;37;37;DSR;DSR;37;37;37
Total;74;111;111;111;111;111;111
Total c/ Over 20%;89;133;133;133;133;133;133
Presentes;74;111;111;111;111;111;111
HC S&OP;0;0;0;0;0;0;0
Folga;-74;-111;-111;-111;-111;-111;-111

2a semana (05/07 a 11/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;37;37;37;37;37;DSR
B;37;37;37;37;DSR;DSR;37
C;37;37;DSR;DSR;37;37;37
D;DSR;DSR;37;37;37;37;37
Total;74;111;111;111;111;111;111
Total c/ Over 20%;89;133;133;133;133;133;133
Presentes;74;111;111;111;111;111;111
HC S&OP;0;0;0;0;0;0;0
Folga;-74;-111;-111;-111;-111;-111;-111

3a semana (12/07 a 18/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;37;37;37;37;DSR;DSR;37
B;37;37;DSR;DSR;37;37;37
C;DSR;DSR;37;37;37;37;37
D;DSR;37;37;37;37;37;DSR
Total;74;111;111;111;111;111;111
Total c/ Over 20%;89;133;133;133;133;133;133
Presentes;74;111;111;111;111;111;111
HC S&OP;0;0;0;0;0;0;0
Folga;-74;-111;-111;-111;-111;-111;-111

4a semana (19/07 a 25/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;37;37;DSR;DSR;37;37;37
B;DSR;DSR;37;37;37;37;37
C;DSR;37;37;37;37;37;DSR
D;37;37;37;37;DSR;DSR;37
Total;74;111;111;111;111;111;111
Total c/ Over 20%;89;133;133;133;133;133;133
Presentes;74;111;111;111;111;111;111
HC S&OP;0;0;0;0;0;0;0
Folga;-74;-111;-111;-111;-111;-111;-111

5a semana (26/07 a 01/08);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;DSR;37;37;37;37;37
B;DSR;37;37;37;37;37;DSR
C;37;37;37;37;DSR;DSR;37
D;37;37;DSR;DSR;37;37;37
Total;74;111;111;111;111;111;111
Total c/ Over 20%;89;133;133;133;133;133;133
Presentes;74;111;111;111;111;111;111
HC S&OP;0;0;0;0;0;0;0
Folga;-74;-111;-111;-111;-111;-111;-111


Escala Julho - Pouso Alegre - SD
Series ativas;A/B/C/D

1a semana (28/06 a 04/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;DSR;5;5;5;5;5
B;DSR;4;4;4;4;4;DSR
C;4;4;4;4;DSR;DSR;4
D;4;4;DSR;DSR;4;4;4
Total;8;12;13;13;13;13;13
Total c/ Over 20%;10;14;16;16;16;16;16
Presentes;8;12;13;13;13;13;13
HC S&OP;0;0;0;0;0;0;0
Folga;-8;-12;-13;-13;-13;-13;-13

2a semana (05/07 a 11/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;5;5;5;5;5;DSR
B;4;4;4;4;DSR;DSR;4
C;4;4;DSR;DSR;4;4;4
D;DSR;DSR;4;4;4;4;4
Total;8;13;13;13;13;13;12
Total c/ Over 20%;10;16;16;16;16;16;14
Presentes;8;13;13;13;13;13;12
HC S&OP;0;0;0;0;0;0;0
Folga;-8;-13;-13;-13;-13;-13;-12

3a semana (12/07 a 18/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;5;5;5;5;DSR;DSR;5
B;4;4;DSR;DSR;4;4;4
C;DSR;DSR;4;4;4;4;4
D;DSR;4;4;4;4;4;DSR
Total;9;13;13;13;12;12;13
Total c/ Over 20%;11;16;16;16;14;14;16
Presentes;9;13;13;13;12;12;13
HC S&OP;0;0;0;0;0;0;0
Folga;-9;-13;-13;-13;-12;-12;-13

4a semana (19/07 a 25/07);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;5;5;DSR;DSR;5;5;5
B;DSR;DSR;4;4;4;4;4
C;DSR;4;4;4;4;4;DSR
D;4;4;4;4;DSR;DSR;4
Total;9;13;12;12;13;13;13
Total c/ Over 20%;11;16;14;14;16;16;16
Presentes;9;13;12;12;13;13;13
HC S&OP;0;0;0;0;0;0;0
Folga;-9;-13;-12;-12;-13;-13;-13

5a semana (26/07 a 01/08);DOM;SEG;TER;QUA;QUI;SEX;SAB
A;DSR;DSR;5;5;5;5;5
B;DSR;4;4;4;4;4;DSR
C;4;4;4;4;DSR;DSR;4
D;4;4;DSR;DSR;4;4;4
Total;8;12;13;13;13;13;13
Total c/ Over 20%;10;14;16;16;16;16;16
Presentes;8;12;13;13;13;13;13
HC S&OP;0;0;0;0;0;0;0
Folga;-8;-12;-13;-13;-13;-13;-13

`;

/* ============ dicionário de códigos ============ */
const CODE_INFO = {
  P:   { label: "Presente",                color: "#3fb96b", bg: "rgba(63,185,107,.14)",  group: "present" },
  F:   { label: "Falta injustificada",     color: "#ef5b62", bg: "rgba(239,91,98,.14)",   group: "absent"  },
  FJ:  { label: "Falta justificada",       color: "#9d7bf0", bg: "rgba(157,123,240,.14)", group: "absent"  },
  AM:  { label: "Atestado médico",         color: "#d9902b", bg: "rgba(217,144,43,.14)",  group: "absent"  },
  AF:  { label: "Afastamento",             color: "#e0484d", bg: "rgba(224,72,77,.14)",   group: "absent"  },
  AL:  { label: "Afastamento longo",       color: "#c23640", bg: "rgba(194,54,64,.16)",   group: "absent"  },
  AB:  { label: "Abandono",                color: "#ff5c5c", bg: "rgba(255,92,92,.14)",   group: "absent"  },
  BH:  { label: "Banco de Horas",          color: "#6a6af0", bg: "rgba(106,106,240,.14)", group: "planned" },
  FO:  { label: "Folga",                   color: "#2fb4b8", bg: "rgba(47,180,184,.14)",  group: "planned" },
  FE:  { label: "Férias",                  color: "#40c07a", bg: "rgba(64,192,122,.14)",  group: "planned" },
  DSR: { label: "Descanso Semanal",        color: "#3d9a72", bg: "rgba(61,154,114,.14)",  group: "dsr"     },
  DV:  { label: "Deslig. voluntário",      color: "#8b93a1", bg: "rgba(139,147,161,.14)", group: "off"     },
  DF:  { label: "Deslig. forçado",         color: "#d06a72", bg: "rgba(208,106,114,.14)", group: "off"     },
  DP:  { label: "Deslig. programado",      color: "#5a9bd4", bg: "rgba(90,155,212,.14)",  group: "off"     },
  "":  { label: "Sem registro",            color: "#5d6a7d", bg: "rgba(93,106,125,.12)",  group: "none"    },
};
const codeInfo = (c) => CODE_INFO[c] || { label: c, color: "#c8cede", bg: "rgba(200,206,222,.12)", group: "other" };

const WEEKDAYS = ["DOM", "SEG", "TER", "QUA", "QUI", "SEX", "SÁB"];

/* ============ parse: CSV de escala (modelo 2) ============ */
function parseEscalaCsv(text) {
  const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/);
  const sections = [];
  let cur = null;
  let curWeek = null;
  const weekRe = /^(.*?)\s*\((\d{2})\/(\d{2})\s*a\s*(\d{2})\/(\d{2})\)$/;

  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i].trim();
    if (!raw) { curWeek = null; continue; }
    const cells = raw.split(";").map((c) => c.trim());

    if (cells.length === 1 && !raw.includes(";")) {
      // possível título de seção (linha seguinte deve ser "Series ativas")
      const next = (lines[i + 1] || "").trim();
      if (/^series?\s+ativas/i.test(next)) {
        const parts = raw.split(" - ");
        cur = { title: raw, name: parts[parts.length - 1] || raw, series: [], weeks: [] };
        sections.push(cur);
        curWeek = null;
      }
      continue;
    }
    if (!cur) continue;

    if (/^series?\s+ativas/i.test(cells[0])) {
      cur.series = (cells[1] || "").split("/").map((s) => s.trim()).filter(Boolean);
      continue;
    }

    const wm = cells[0].match(weekRe);
    if (wm && cells[1] === "DOM") {
      curWeek = {
        label: cells[0],
        shortLabel: wm[1].trim(),
        start: { d: +wm[2], m: +wm[3] },
        end: { d: +wm[4], m: +wm[5] },
        rows: {},   // série -> [7 valores: "DSR" | número]
        totals: null,
      };
      cur.weeks.push(curWeek);
      continue;
    }
    if (!curWeek) continue;

    if (/^[A-Z]$/.test(cells[0])) {
      curWeek.rows[cells[0]] = cells.slice(1, 8).map((v) => (v.toUpperCase() === "DSR" ? "DSR" : Number(v)));
    } else if (/^total$/i.test(cells[0])) {
      curWeek.totals = cells.slice(1, 8).map(Number);
    }
  }
  return sections.filter((s) => s.weeks.length);
}

/* ============ parse: aba de absenteísmo (modelo 1) ============ */
function parseAbsSheet(ws) {
  const grid = XLSX.utils.sheet_to_json(ws, { header: 1, defval: "" });
  let hi = -1;
  for (let i = 0; i < Math.min(grid.length, 12); i++) {
    const row = grid[i].map((c) => String(c));
    if (row.some((c) => /^nome$/i.test(c.trim())) && row.some((c) => /^turno$/i.test(c.trim()))) { hi = i; break; }
  }
  if (hi < 0) return { error: "Não encontrei as colunas 'Nome' e 'Turno' nesta aba." };
  const header = grid[hi].map((c) => String(c));
  const idx = (re) => header.findIndex((c) => re.test(c.trim()));
  const nameI = idx(/^nome$/i), turnoI = idx(/^turno$/i), cargoI = idx(/^cargo$/i), lidI = idx(/^lideran/i);
  const dayCols = {};
  header.forEach((h, i) => {
    const m = h.trim().match(/^(\d{1,2})\s/);
    if (m) dayCols[+m[1]] = i;
  });
  if (!Object.keys(dayCols).length) return { error: "Não encontrei colunas de dias (ex.: '1 Qua') nesta aba." };

  const emps = [];
  for (let r = hi + 1; r < grid.length; r++) {
    const row = grid[r];
    const nome = String(row[nameI] || "").trim();
    if (!nome) continue;
    const days = [];
    for (let d = 1; d <= 31; d++) days.push(dayCols[d] != null ? String(row[dayCols[d]] || "").trim().toUpperCase() : "");
    emps.push([nome, String(row[turnoI] || "").trim().toUpperCase() || "?", String(cargoI >= 0 ? row[cargoI] : "").trim(), String(lidI >= 0 ? row[lidI] : "").trim(), days.join("|")]);
  }
  return { emps };
}

/* ============ datas ============ */
function buildWeekDates(week, year) {
  const start = new Date(year, week.start.m - 1, week.start.d);
  return Array.from({ length: 7 }, (_, i) => {
    const dt = new Date(start);
    dt.setDate(start.getDate() + i);
    return { d: dt.getDate(), m: dt.getMonth() + 1 };
  });
}
function detectMainMonth(section, year) {
  const freq = {};
  section.weeks.forEach((w) => buildWeekDates(w, year).forEach(({ m }) => (freq[m] = (freq[m] || 0) + 1)));
  return +Object.entries(freq).sort((a, b) => b[1] - a[1])[0][0];
}

/* ============ cruzamento escala × pessoas ============ */
function buildCell(escVal, date, mainMonth, serie, emps) {
  const inMonth = date.m === mainMonth && date.d >= 1 && date.d <= 31;
  const people = [];
  const counts = { present: 0, absent: 0, planned: 0, dsr: 0, off: 0, none: 0, other: 0 };
  if (inMonth) {
    for (const e of emps) {
      if (e[1] !== serie) continue;
      const code = e[4].split("|")[date.d - 1] || "";
      const g = codeInfo(code).group;
      counts[g] = (counts[g] || 0) + 1;
      people.push({ nome: e[0], cargo: e[2], lider: e[3], code });
    }
  }
  const alerts = [];
  if (!inMonth) {
    alerts.push({ sev: "muted", msg: "Fora do mês da planilha — sem dados de presença." });
  } else if (escVal === "DSR") {
    if (counts.present > 0) alerts.push({ sev: "red", msg: `${counts.present} pessoa(s) marcadas como presentes em dia de DSR da série — não faz sentido.` });
    if (counts.absent > 0) alerts.push({ sev: "info", msg: `${counts.absent} ausência(s) registradas em dia de DSR da série.` });
  } else if (typeof escVal === "number") {
    const active = people.length - counts.off - counts.none;
    if (active === 0 && people.length === 0) {
      alerts.push({ sev: "red", msg: "Nenhuma pessoa encontrada nesta série na planilha." });
    } else {
      const gap = counts.present - escVal;
      if (gap < 0) alerts.push({ sev: gap <= -Math.ceil(escVal * 0.2) ? "red" : "amber", msg: `Faltam ${-gap} para a meta de ${escVal} (presentes: ${counts.present}).` });
      if (gap > 0) alerts.push({ sev: "blue", msg: `Excede a meta de ${escVal} em ${gap} pessoa(s) (presentes: ${counts.present}).` });
      if (counts.dsr > 0) alerts.push({ sev: "info", msg: `${counts.dsr} com DSR individual em dia de trabalho da série.` });
    }
  }
  return { escVal, date, serie, inMonth, people, counts, alerts };
}

/* ============ UI helpers ============ */
const sevColor = { red: "#ef5b62", amber: "#e2a63b", blue: "#5a9bd4", info: "#8b93a1", muted: "#5d6a7d" };

function Chip({ code, small }) {
  const info = codeInfo(code);
  return (
    <span style={{
      display: "inline-block", padding: small ? "1px 6px" : "2px 8px", borderRadius: 4,
      fontSize: small ? 10 : 11, fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
      fontWeight: 700, letterSpacing: ".04em", color: info.color, background: info.bg,
      border: `1px solid ${info.color}44`,
    }}>{code || "—"}</span>
  );
}

function DiffBadge({ gap }) {
  const c = gap === 0 ? "#3fb96b" : gap < 0 ? "#e2a63b" : "#5a9bd4";
  return (
    <span style={{ fontSize: 10, fontWeight: 800, color: c, fontFamily: "ui-monospace, monospace" }}>
      {gap > 0 ? `+${gap}` : gap}
    </span>
  );
}

/* ============ componente principal ============ */
export default function EscalaApp() {
  const [wb, setWb] = useState(null);
  const [sheetName, setSheetName] = useState("");
  const [emps, setEmps] = useState(null);
  const [empsSource, setEmpsSource] = useState("");
  const [escSections, setEscSections] = useState(null);
  const [escSource, setEscSource] = useState("");
  const [sectionName, setSectionName] = useState("");
  const [year, setYear] = useState(2026);
  const [openCell, setOpenCell] = useState(null); // {wi, serie, di}
  const [errors, setErrors] = useState([]);
  const xlsxRef = useRef(null), csvRef = useRef(null);

  const pushError = (m) => setErrors((e) => [...e, m]);

  const loadExample = () => {
    setErrors([]);
    setEmps(EXAMPLE_EMPS); setEmpsSource("Exemplo · aba PASVC Jul"); setWb(null); setSheetName("PASVC Jul");
    const secs = parseEscalaCsv(EXAMPLE_ESCALA_CSV);
    setEscSections(secs); setEscSource("Exemplo · escala Pouso Alegre Julho");
    setSectionName(secs[0]?.name || ""); setOpenCell(null);
  };

  const onXlsx = async (file) => {
    setErrors([]);
    try {
      const buf = await file.arrayBuffer();
      const w = XLSX.read(buf);
      setWb(w); setEmpsSource(file.name);
      const first = w.SheetNames[0];
      setSheetName(first);
      const r = parseAbsSheet(w.Sheets[first]);
      if (r.error) { pushError(`${first}: ${r.error}`); setEmps(null); } else setEmps(r.emps);
      setOpenCell(null);
    } catch (e) { pushError("Falha ao ler o .xlsx: " + e.message); }
  };
  const pickSheet = (name) => {
    setSheetName(name); setOpenCell(null);
    if (!wb) return;
    const r = parseAbsSheet(wb.Sheets[name]);
    if (r.error) { pushError(`${name}: ${r.error}`); setEmps(null); } else setEmps(r.emps);
  };
  const onCsv = async (file) => {
    setErrors([]);
    try {
      const text = await file.text();
      const secs = parseEscalaCsv(text);
      if (!secs.length) { pushError("Não encontrei blocos de escala no CSV (esperado o modelo com 'Series ativas' e semanas)."); return; }
      setEscSections(secs); setEscSource(file.name); setSectionName(secs[0].name); setOpenCell(null);
    } catch (e) { pushError("Falha ao ler o CSV: " + e.message); }
  };

  const section = useMemo(() => escSections?.find((s) => s.name === sectionName) || null, [escSections, sectionName]);
  const mainMonth = useMemo(() => (section ? detectMainMonth(section, year) : null), [section, year]);

  const model = useMemo(() => {
    if (!section || !emps) return null;
    const weeks = section.weeks.map((w, wi) => {
      const dates = buildWeekDates(w, year);
      const series = section.series.length ? section.series : Object.keys(w.rows);
      const rows = series.map((s) => ({
        serie: s,
        cells: dates.map((date, di) => buildCell(w.rows[s]?.[di], date, mainMonth, s, emps)),
      }));
      return { ...w, wi, dates, rows };
    });
    return { weeks };
  }, [section, emps, year, mainMonth]);

  const noSerie = useMemo(() => {
    if (!emps || !section) return [];
    const valid = new Set(section.series);
    return emps.filter((e) => !valid.has(e[1]));
  }, [emps, section]);

  const stats = useMemo(() => {
    if (!model) return null;
    let red = 0, amber = 0, blue = 0;
    model.weeks.forEach((w) => w.rows.forEach((r) => r.cells.forEach((c) => c.alerts.forEach((a) => {
      if (a.sev === "red") red++; else if (a.sev === "amber") amber++; else if (a.sev === "blue") blue++;
    }))));
    return { red, amber, blue };
  }, [model]);

  const serieCounts = useMemo(() => {
    if (!emps) return {};
    const m = {};
    emps.forEach((e) => (m[e[1]] = (m[e[1]] || 0) + 1));
    return m;
  }, [emps]);

  /* ---------- estilos base ---------- */
  const S = {
    page: { minHeight: "100vh", background: "#0b111c", color: "#dfe5f1", fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif", padding: "20px 22px 60px" },
    panel: { background: "#101827", border: "1px solid #1d2739", borderRadius: 10 },
    btn: { background: "#182338", border: "1px solid #2a3852", color: "#dfe5f1", borderRadius: 7, padding: "7px 13px", fontSize: 13, cursor: "pointer", fontWeight: 600 },
    select: { background: "#0d1420", border: "1px solid #2a3852", color: "#dfe5f1", borderRadius: 7, padding: "6px 9px", fontSize: 13 },
    mono: { fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace" },
  };

  return (
    <div style={S.page}>
      {/* cabeçalho */}
      <div style={{ display: "flex", alignItems: "baseline", gap: 14, flexWrap: "wrap", marginBottom: 14 }}>
        <h1 style={{ margin: 0, fontSize: 21, fontWeight: 800, letterSpacing: "-0.01em" }}>
          Distribuição de escala <span style={{ color: "#5a9bd4" }}>× absenteísmo</span>
        </h1>
        <span style={{ fontSize: 12, color: "#8b93a1" }}>
          Cruza a escala das séries (A/B/C/D) com a presença real, dia a dia. Clique numa célula para explodir o detalhe.
        </span>
      </div>

      {/* controles */}
      <div style={{ ...S.panel, padding: 12, display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center", marginBottom: 10 }}>
        <button style={{ ...S.btn, background: "#1c3050", borderColor: "#33507e" }} onClick={loadExample}>
          ▶ Carregar exemplo (PA SVC · Julho)
        </button>
        <span style={{ width: 1, height: 24, background: "#1d2739" }} />
        <input ref={xlsxRef} type="file" accept=".xlsx,.xlsm" style={{ display: "none" }} onChange={(e) => e.target.files[0] && onXlsx(e.target.files[0])} />
        <button style={S.btn} onClick={() => xlsxRef.current.click()}>1 · Planilha de absenteísmo (.xlsx)</button>
        {wb && (
          <select style={S.select} value={sheetName} onChange={(e) => pickSheet(e.target.value)}>
            {wb.SheetNames.map((n) => <option key={n} value={n}>{n}</option>)}
          </select>
        )}
        <input ref={csvRef} type="file" accept=".csv,.txt" style={{ display: "none" }} onChange={(e) => e.target.files[0] && onCsv(e.target.files[0])} />
        <button style={S.btn} onClick={() => csvRef.current.click()}>2 · Escala do site (.csv)</button>
        {escSections && (
          <select style={S.select} value={sectionName} onChange={(e) => { setSectionName(e.target.value); setOpenCell(null); }}>
            {escSections.map((s) => <option key={s.name} value={s.name}>{s.name} — {s.title.replace(/ - [^-]+$/, "")}</option>)}
          </select>
        )}
        <label style={{ fontSize: 12, color: "#8b93a1", marginLeft: "auto" }}>
          Ano{" "}
          <input type="number" value={year} onChange={(e) => setYear(+e.target.value || 2026)}
            style={{ ...S.select, width: 70, ...S.mono }} />
        </label>
      </div>

      {/* fontes carregadas + erros */}
      {(empsSource || escSource) && (
        <div style={{ fontSize: 12, color: "#8b93a1", marginBottom: 8, display: "flex", gap: 16, flexWrap: "wrap" }}>
          {empsSource && <span>Presenças: <b style={{ color: "#c8cede" }}>{empsSource}{wb ? ` · aba ${sheetName}` : ""}</b> {emps && `(${emps.length} pessoas)`}</span>}
          {escSource && <span>Escala: <b style={{ color: "#c8cede" }}>{escSource}</b>{section && ` · ${section.name} · séries ${section.series.join("/")}`}</span>}
          {mainMonth && <span>Mês detectado: <b style={{ color: "#c8cede" }}>{String(mainMonth).padStart(2, "0")}/{year}</b></span>}
        </div>
      )}
      {errors.map((e, i) => (
        <div key={i} style={{ ...S.panel, borderColor: "#ef5b6255", background: "#1c1016", padding: "8px 12px", fontSize: 13, color: "#ef9ba0", marginBottom: 8 }}>⚠ {e}</div>
      ))}

      {/* legenda */}
      <div style={{ ...S.panel, padding: "8px 12px", display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center", marginBottom: 12, fontSize: 11 }}>
        {Object.entries(CODE_INFO).filter(([c]) => c !== "").map(([c, info]) => (
          <span key={c} style={{ display: "inline-flex", alignItems: "center", gap: 5, color: "#aeb6c6" }}>
            <Chip code={c} small /> {info.label}
          </span>
        ))}
        <span style={{ display: "inline-flex", alignItems: "center", gap: 5, color: "#aeb6c6" }}><Chip code="" small /> Sem registro</span>
      </div>

      {/* resumo */}
      {emps && section && (
        <div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginBottom: 16, fontSize: 12 }}>
          <div style={{ ...S.panel, padding: "6px 12px" }}>
            <b style={{ ...S.mono, fontSize: 15 }}>{emps.length}</b> <span style={{ color: "#8b93a1" }}>pessoas na aba</span>
          </div>
          {section.series.map((s) => (
            <div key={s} style={{ ...S.panel, padding: "6px 12px" }}>
              <b style={{ color: "#5a9bd4" }}>Série {s}</b>{" "}
              <b style={{ ...S.mono, fontSize: 15 }}>{serieCounts[s] || 0}</b>
            </div>
          ))}
          {stats && (
            <div style={{ ...S.panel, padding: "6px 12px", display: "flex", gap: 12 }}>
              <span style={{ color: sevColor.red }}>● {stats.red} críticos</span>
              <span style={{ color: sevColor.amber }}>● {stats.amber} déficits</span>
              <span style={{ color: sevColor.blue }}>● {stats.blue} excedentes</span>
            </div>
          )}
        </div>
      )}

      {/* aviso: pessoas sem série válida */}
      {noSerie.length > 0 && (
        <div style={{ ...S.panel, borderColor: "#e2a63b55", background: "#1a1610", padding: "8px 12px", fontSize: 12, color: "#e2c08a", marginBottom: 14 }}>
          ⚠ {noSerie.length} pessoa(s) com turno fora das séries ativas ({section.series.join("/")}) e que ficaram fora da distribuição:{" "}
          {noSerie.map((e) => `${e[0]} (${e[1]})`).join(" · ")}
        </div>
      )}

      {/* estado vazio */}
      {!model && !errors.length && (
        <div style={{ ...S.panel, padding: 40, textAlign: "center", color: "#8b93a1", fontSize: 14 }}>
          Envie a planilha de absenteísmo e o CSV de escala — ou use o botão <b style={{ color: "#c8cede" }}>Carregar exemplo</b> para ver o caso Pouso Alegre SVC.
        </div>
      )}

      {/* semanas */}
      {model?.weeks.map((w) => (
        <div key={w.wi} style={{ ...S.panel, marginBottom: 18, overflow: "hidden" }}>
          <div style={{ padding: "9px 14px", borderBottom: "1px solid #1d2739", display: "flex", alignItems: "center", gap: 10 }}>
            <b style={{ fontSize: 14 }}>{w.label}</b>
            <span style={{ fontSize: 11, color: "#8b93a1" }}>meta/dia por série conforme escala · presença real da aba</span>
          </div>
          <div style={{ overflowX: "auto" }}>
            <table style={{ borderCollapse: "collapse", width: "100%", minWidth: 780 }}>
              <thead>
                <tr>
                  <th style={{ padding: "7px 10px", fontSize: 11, color: "#8b93a1", textAlign: "left", borderBottom: "1px solid #1d2739", width: 74 }}>Série</th>
                  {w.dates.map((dt, di) => (
                    <th key={di} style={{ padding: "7px 6px", fontSize: 11, color: "#8b93a1", borderBottom: "1px solid #1d2739" }}>
                      {WEEKDAYS[di]}
                      <div style={{ ...S.mono, fontSize: 12, color: "#c8cede" }}>
                        {String(dt.d).padStart(2, "0")}/{String(dt.m).padStart(2, "0")}
                      </div>
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {w.rows.map((row) => (
                  <React.Fragment key={row.serie}>
                    <tr>
                      <td style={{ padding: "6px 10px", borderBottom: "1px solid #16203100", fontWeight: 800, color: "#5a9bd4", fontSize: 14 }}>
                        {row.serie}
                        <div style={{ fontSize: 10, color: "#5d6a7d", fontWeight: 500 }}>{serieCounts[row.serie] || 0} pessoas</div>
                      </td>
                      {row.cells.map((cell, di) => {
                        const isOpen = openCell && openCell.wi === w.wi && openCell.serie === row.serie && openCell.di === di;
                        const isDsr = cell.escVal === "DSR";
                        const hasRed = cell.alerts.some((a) => a.sev === "red");
                        const hasAmber = cell.alerts.some((a) => a.sev === "amber");
                        const hasBlue = cell.alerts.some((a) => a.sev === "blue");
                        const border = hasRed ? "#ef5b62" : hasAmber ? "#e2a63b" : hasBlue ? "#5a9bd4" : isDsr ? "#2a5d47" : "#26518a";
                        const gap = typeof cell.escVal === "number" ? cell.counts.present - cell.escVal : null;
                        return (
                          <td key={di} style={{ padding: 4, verticalAlign: "top" }}>
                            <button
                              onClick={() => setOpenCell(isOpen ? null : { wi: w.wi, serie: row.serie, di })}
                              title={cell.alerts.map((a) => a.msg).join("\n") || "Sem alertas"}
                              style={{
                                width: "100%", minHeight: 56, cursor: cell.inMonth ? "pointer" : "default",
                                background: isOpen ? "#1b2740" : !cell.inMonth ? "#0d1420" : isDsr ? "#0f1a17" : "#0f1726",
                                border: `1px solid ${!cell.inMonth ? "#1d2739" : border}${isOpen ? "" : "66"}`,
                                borderRadius: 7, padding: "5px 7px", color: "inherit", textAlign: "left",
                                boxShadow: isOpen ? `0 0 0 1px ${border}` : "none", position: "relative",
                              }}
                            >
                              {!cell.inMonth ? (
                                <span style={{ fontSize: 10, color: "#42506a" }}>{isDsr ? "DSR" : cell.escVal} · fora do mês</span>
                              ) : isDsr ? (
                                <>
                                  <span style={{ fontSize: 12, fontWeight: 800, color: "#3d9a72", letterSpacing: ".05em" }}>DSR</span>
                                  {cell.counts.present > 0 && (
                                    <div style={{ fontSize: 10, color: "#ef5b62", fontWeight: 700 }}>⚠ {cell.counts.present} presentes</div>
                                  )}
                                  {cell.counts.absent > 0 && <div style={{ fontSize: 10, color: "#8b93a1" }}>{cell.counts.absent} ausências</div>}
                                </>
                              ) : (
                                <>
                                  <div style={{ display: "flex", alignItems: "baseline", gap: 5 }}>
                                    <span style={{ ...S.mono, fontSize: 15, fontWeight: 800, color: hasRed ? "#ef5b62" : hasAmber ? "#e2a63b" : "#3fb96b" }}>
                                      {cell.counts.present}
                                    </span>
                                    <span style={{ fontSize: 10, color: "#5d6a7d" }}>/ {cell.escVal}</span>
                                    {gap !== null && gap !== 0 && <DiffBadge gap={gap} />}
                                  </div>
                                  <div style={{ fontSize: 9.5, color: "#8b93a1", marginTop: 2 }}>
                                    {cell.counts.absent > 0 && <span style={{ color: "#ef9ba0" }}>{cell.counts.absent} aus · </span>}
                                    {cell.counts.dsr > 0 && <span>{cell.counts.dsr} dsr · </span>}
                                    {cell.counts.planned > 0 && <span>{cell.counts.planned} prog · </span>}
                                    {cell.counts.none > 0 && <span style={{ color: "#42506a" }}>{cell.counts.none} s/reg</span>}
                                  </div>
                                </>
                              )}
                              {cell.inMonth && cell.alerts.some((a) => a.sev !== "info") && (
                                <span style={{ position: "absolute", top: 5, right: 6, width: 7, height: 7, borderRadius: "50%", background: border }} />
                              )}
                            </button>
                          </td>
                        );
                      })}
                    </tr>
                    {openCell && openCell.wi === w.wi && openCell.serie === row.serie && (
                      <tr>
                        <td colSpan={8} style={{ padding: "0 8px 12px" }}>
                          <CellDetail cell={row.cells[openCell.di]} onClose={() => setOpenCell(null)} S={S} />
                        </td>
                      </tr>
                    )}
                  </React.Fragment>
                ))}
                {/* totais do dia */}
                <tr>
                  <td style={{ padding: "6px 10px", fontSize: 11, color: "#8b93a1", borderTop: "1px solid #1d2739" }}>Total dia</td>
                  {w.dates.map((dt, di) => {
                    const target = w.rows.reduce((s, r) => s + (typeof r.cells[di].escVal === "number" ? r.cells[di].escVal : 0), 0);
                    const pres = w.rows.reduce((s, r) => s + (r.cells[di].inMonth ? r.cells[di].counts.present : 0), 0);
                    const anyIn = w.rows.some((r) => r.cells[di].inMonth);
                    return (
                      <td key={di} style={{ padding: "6px", borderTop: "1px solid #1d2739", textAlign: "center", fontSize: 11 }}>
                        {anyIn ? (
                          <span style={S.mono}>
                            <b style={{ color: pres >= target ? "#3fb96b" : "#e2a63b" }}>{pres}</b>
                            <span style={{ color: "#5d6a7d" }}> / {target}</span>
                          </span>
                        ) : <span style={{ color: "#42506a" }}>—</span>}
                      </td>
                    );
                  })}
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      ))}
    </div>
  );
}

/* ============ painel de detalhe ("explosão" da célula) ============ */
function CellDetail({ cell, onClose, S }) {
  const groups = [
    { key: "present", title: "Presentes" },
    { key: "absent", title: "Ausências" },
    { key: "dsr", title: "Descanso (DSR)" },
    { key: "planned", title: "Programado (FE / FO / BH)" },
    { key: "off", title: "Desligados" },
    { key: "none", title: "Sem registro" },
  ];
  const byGroup = {};
  cell.people.forEach((p) => {
    const g = codeInfo(p.code).group;
    (byGroup[g] = byGroup[g] || []).push(p);
  });
  Object.values(byGroup).forEach((arr) => arr.sort((a, b) => a.nome.localeCompare(b.nome)));

  return (
    <div style={{ background: "#0d1420", border: "1px solid #2a3852", borderRadius: 9, padding: 14 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 10, flexWrap: "wrap" }}>
        <b style={{ fontSize: 14 }}>
          Série {cell.serie} · {String(cell.date.d).padStart(2, "0")}/{String(cell.date.m).padStart(2, "0")} ·{" "}
          {cell.escVal === "DSR" ? "DSR da série" : `meta ${cell.escVal}`}
        </b>
        <span style={{ fontSize: 12, color: "#8b93a1" }}>
          {cell.counts.present} presentes · {cell.counts.absent} ausências · {cell.counts.dsr} DSR · {cell.counts.off} desligados · {cell.counts.none} sem registro
        </span>
        <button onClick={onClose} style={{ marginLeft: "auto", background: "none", border: "1px solid #2a3852", color: "#8b93a1", borderRadius: 6, padding: "3px 10px", cursor: "pointer", fontSize: 12 }}>
          Fechar ✕
        </button>
      </div>

      {cell.alerts.length > 0 && (
        <div style={{ display: "flex", flexDirection: "column", gap: 5, marginBottom: 12 }}>
          {cell.alerts.map((a, i) => (
            <div key={i} style={{ fontSize: 12.5, color: sevColor[a.sev], display: "flex", gap: 7, alignItems: "center" }}>
              <span style={{ width: 7, height: 7, borderRadius: "50%", background: sevColor[a.sev], flexShrink: 0 }} />
              {a.msg}
            </div>
          ))}
        </div>
      )}

      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))", gap: 12 }}>
        {groups.map((g) => {
          const arr = byGroup[g.key];
          if (!arr?.length) return null;
          return (
            <div key={g.key} style={{ background: "#101827", border: "1px solid #1d2739", borderRadius: 8, padding: 10 }}>
              <div style={{ fontSize: 11, fontWeight: 800, color: "#8b93a1", letterSpacing: ".06em", textTransform: "uppercase", marginBottom: 8 }}>
                {g.title} <span style={{ color: "#5a9bd4" }}>· {arr.length}</span>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: 4, maxHeight: 260, overflowY: "auto" }}>
                {arr.map((p, i) => (
                  <div key={i} title={`${p.cargo}${p.lider ? " · Líder: " + p.lider : ""}`}
                    style={{ display: "flex", alignItems: "center", gap: 8, fontSize: 12.5, padding: "3px 4px", borderRadius: 5 }}>
                    <Chip code={p.code} small />
                    <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{p.nome}</span>
                  </div>
                ))}
              </div>
            </div>
          );
        })}
        {cell.people.length === 0 && <div style={{ fontSize: 13, color: "#8b93a1" }}>Nenhuma pessoa nesta série / dia.</div>}
      </div>
    </div>
  );
}
